# Generated by Django 5.2.5 on 2025-09-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField(blank=True)),
                ('source', models.CharField(max_length=255)),
                ('url', models.URLField(unique=True)),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['published_at'], name='news_newsar_publish_df29a9_idx'), models.Index(fields=['source'], name='news_newsar_source_2a5eed_idx')],
                'constraints': [models.UniqueConstraint(fields=('title', 'source'), name='uniq_title_source')],
            },
        ),
    ]
